---
version: '3.9'

services:
  firefox_service:
    image: selenium/standalone-firefox:latest
    container_name: firefox_service
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    environment:
      - TZ=UTC
    healthcheck:
      test: curl -f http://localhost:4444
      interval: 10s
      retries: 5

  openai_with_twitter_backend:
    image: spring/openai-with-twitter-backend
    container_name: openai-with-twitter-backend
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    depends_on:
      firefox_service:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      - TWITTER_BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAN8ciQEAAAAA7i9tiijl4fry1WkTu%2Fw1k2O0s%2B4%3DOnCPXFsX91G6xt8AinJHmYdTLnOEYs521H73XKYCTjNlyKacjx
      - OPENAI_BEARER_TOKEN=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
      - TWITTER_CLIENT_KEY=dVpUeFljYWpKOTN6S0hpbE5TWFc6MTpjaQ
      - TWITTER_CLIENT_SECRET=__Q87oseG17MO0Ex5pLpqUvYLdZLBx9mZ-DyIAxJaKY85dm80W
