---
version: '3.7'
services:
  crypto-backend:
    image: 'spring/crypto-api'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://crypto-prod-db:5432/postgres?currentSchema=cyrpto-api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword.
      - TWITTER_BEARER_TOKEN=
      - KUCOIN_API_KEY=
      - KUCOIN_API_SECRET=
      - KUCOIN_API_PASS_PHRASE=
      - OPENAI_BEARER_TOKEN=
  prometheus:
    image: prom/prometheus:v2.40.4
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  db:
    image: postgres:15.0-alpine
    container_name: crypto-prod-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword.

volumes:
  prometheus-data:
  grafana-storage: