server:
  forward-headers-strategy: native
  servlet:
    context-path: /api
  port: 8082

app:
  with-openai: ${APP_WITH_OPENAI}

openai:
  api-root: https://api.openai.com
  client-token: ${OPENAI_BEARER_TOKEN}
  model: text-davinci-003

