server:
  forward-headers-strategy: native
  servlet:
    context-path: /api
  port: 8082

openai:
  api-root: https://api.openai.com
  client-token: ${OPENAI_BEARER_TOKEN}
  model: text-davinci-002

springdoc:
  swagger-ui:
    path: /swagger

spring:
  #In order to execute swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
