server:
  forward-headers-strategy: native
  servlet:
    context-path: /api
  port: 8082

app:
  schedule:
    twitter-fixed-delay-expression: 0 0 12,15,19 * * *

twitter:
  api-root: https://api.twitter.com/2/
  client-token: ${TWITTER_BEARER_TOKEN}
  client-key: ${TWITTER_CLIENT_KEY}
  client-secret: ${TWITTER_CLIENT_SECRET}
  callback-url: http://www.example.com/callback
  influencers-list: elonmusk,garyvee,sama,tonyvalormusic,InspiringThinkn,BrendonBurchard
  tweets-max-results: 10

openai:
  api-root: https://api.openai.com
  client-token: ${OPENAI_BEARER_TOKEN}
  model: text-davinci-002

springdoc:
  swagger-ui:
    path: /swagger

spring:
  #In order to execute swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
