server:
  servlet:
    context-path: /api
  port: 8082

app:
  schedule:
    twitter-post-cron-expression: 0 30 12,15,16,19 * * *
    twitter-replies-cron-expression: 0 0/5 * * * *
    twitter-amazon-affiliate-program-cron-expression: 0 0/1 * * * *

twitter:
  api-root: https://api.twitter.com/2/
  client-token: ${TWITTER_BEARER_TOKEN}
  client-key: ${TWITTER_CLIENT_KEY}
  client-secret: ${TWITTER_CLIENT_SECRET}
  callback-url: http://www.example.com/callback
  influencers-list: elonmusk,garyvee,sama,tonyvalormusic,InspiringThinkn,BrendonBurchard,leeerob,addyosmani,ErikSolheim
  tweets-max-results: 10

openai:
  api-root: https://api.openai.com
  client-token: ${OPENAI_BEARER_TOKEN}
  model: gpt-3.5-turbo

springdoc:
  swagger-ui:
    path: /swagger

spring:
  #In order to execute swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus